
name: setting up environment

on: [push]
    
env:
 username: CyberJalagam
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           git clone https://github.com/CyberJalagam/android_rom_building_scripts scripts && cd scripts && chmod +x env.sh && chmod +x git.sh && chmod +x full_build_script.sh && chmod +x gdrive.sh && ./git.sh && ./env.sh
